-- DESAFIO 1
/*
QUANTAS PESSOAS TEM O MESMO MIDDLENAME AGRUPADAS POR MIDDLENAME
*/

SELECT MiddleName, COUNT(MiddleName) AS "QNTD"
FROM Person.Person
GROUP BY MiddleName;

-- DESAFIO 2
/*
SABER EM MÉDIA A QUANTIDADE QUE CADA PRODUTO É VENDIDO NA LOJA
*/

SELECT ProductID, AVG(OrderQty) AS "MEDIA"
FROM Sales.SalesOrderDetail
GROUP BY ProductID
ORDER BY ProductID;

-- DESAFIO 3
/*
QUAIS AS 10 VENDAS QUE NO TOTAL TIVERAM OS MAIORES VALOR DE VENDA
(LINE TOTAL) POR PRODUTO DO MAIOR VALOR PARA O MENOR
*/

SELECT TOP 10 ProductID, SUM(LineTotal) AS "TOTAL"
FROM Sales.SalesOrderDetail
GROUP BY ProductID
ORDER BY TOTAL DESC;

-- DESAFIO 4
/*
QUANTOS PRODUTOS E QUAL A QNTD MEDIA DE PRODUTOS TEMOS CADASTRADOS
NAS NOSSAS ORDEM DE SERVICO (WORKORDER), AGRUPADOS POR PRODUCTID
*/

SELECT ProductID, COUNT(ProductID) AS "TOTAL",
AVG(OrderQty) AS "MEDIA"
FROM Production.WorkOrder
GROUP BY ProductID;
