--- DESCOBRIR QUANTAS PESSOAS NÃO TEM CARTÃO DE CREDITO REGISTRADO
SELECT *
FROM Person.Person AS P
LEFT JOIN Sales.PersonCreditCard AS PC
ON P.BusinessEntityID = PC.BusinessEntityID
WHERE PC.BusinessEntityID IS NULL;

--- INNER JOIN: 19 118 (TOTAL COM CARTÃO REGISTRADO)
--- LEFT JOIN: 19 972 (TOTAL PESSOAS)
