-- DESAFIO 1
/*
ENCONTRAR QUAIS AS PROVINICIAS ESTÃO REGISTRADOS NO BANCO DE DADOS
MAIS DO QUE 1000 VEZES
*/

SELECT StateProvinceID, COUNT(StateProvinceID) AS "QUANTIDADE"
FROM Person.Address
GROUP BY StateProvinceID
HAVING COUNT(StateProvinceID) > 1000;

-- DESAFIO 2
/*
QUAIS PRODUTOS NÃO ESTÃO TRAZENDO UMA MÉDIA DE NO MÍNIMO 1 MILHÃO
EM TOTAL DE VENDAS(LINETOTAL)
*/

SELECT ProductID, AVG(LineTotal) AS "MEDIA"
FROM Sales.SalesOrderDetail
GROUP BY ProductID
HAVING AVG(LINETOTAL) < 1000000;


