-- DESAFIO 1
/*
TROCAR O NOME DAS COLUNAS FIRSTNAME E LASTNAME PARA PT-BR
*/

SELECT FirstName AS "NOME",
LastName AS "SOBRENOME"
FROM Person.Person

-- DESAFIO 2
/*
TROCAR O NOME DA COLUNA PRODUCTNUMBER PARA PT-BR
*/

SELECT ProductNumber AS "NÚMERO DO PRODUTO"
FROM Production.Product

-- DESAFIO 3
/*
TROCAR O NOME DA COLUNA UNITPRICE PARA PT-BR
*/

SELECT UNITPRICE AS "PREÇO UNITÁRIO"
FROM Sales.SalesOrderDetail